// ATIVIDADE PRÁTICA: GESTÃO DE ALUNOS COM JAVASCRIPT

console.log("Sistema escolar iniciado!");

// Etapa 1: Declare os dados dos alunos abaixo...

// Etapa 2: Crie a função para calcular a nota final (com bônus)...

// Etapa 3: Verifique se o aluno tem direito a bônus (if/else)...

// Etapa 4: Liste todos os alunos e suas notas (Laço de repetição)...